Repository kubermatic/tail, pull requests merged in 2018-11, with the labels that each got.

#2 Add OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#3 Allow test names to contain numbers
  VERSION
  pkg/handler/handler.go
Labels: approved, lgtm, release-note-none, size/XS

#6 Add issue and PR templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, kind/feature, lgtm, release-note-none, size/M

#7 Redesign login page
  pkg/handler/login.html
Labels: approved, lgtm, release-note, size/M
