Repository kubermatic/tail, pull requests merged in 2019-01, with the labels that each got.

#14 Use `build` as url prefix to fix Deck Spyglass link insertion
  README.md
  VERSION
  manifest.yaml
  pkg/handler/handler.go
  pkg/handler/handler_test.go
Labels: approved, lgtm, release-note-none, size/M

#15 Use gubernator-compatible urls
  cmd/main.go
  pkg/handler/handler.go
  pkg/handler/handler_test.go
Labels: approved, lgtm, release-note, size/M

#17 Fix pathChecker regex to allow numbers in repo names
  VERSION
  pkg/handler/handler.go
  pkg/handler/handler_test.go
Labels: approved, kind/bug, lgtm, release-note, size/XS
